USE [saidattapeetham]
GO

SET IDENTITY_INSERT [saidattapeetham].[dbo].[SEVA_STHALA_FAQ] ON
GO

INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1002,N'I am in India, how can i sponsor for the "Sthala Seva"?',N'For Indian Donors, You may Donate using Credit Card Via Paypal or Transfer Money Rs.666/ Sponsor to the Following  Account No: 043210100142932 IFSC CODE: ANDB0000432 – ANDHRA BANK, PITHAPURAM.',N'2016-02-10 09:18:14 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1003,N'What is "Shirdi In America"?',N'"Shirdi In America" is a divine and responsible project taken up by Sai Datta Peetham to Construct a temple similar to Shirdi(India) in NJ,USA.The project is planned to be completed in two phases:  Phase 1- Acquisition of land(Sthala Seva) for the proposed temple site extending over 23 acres. Phase 1 has commenced now & currently registration for sponsorship of $11 is underway Phase 2:Start of Construction.',N'2016-02-10 09:19:25 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1004,N'What is "Sthala Seva"',N'Contribution towards acquiring the land/space for construction of a Mandir is called Sthala Seva, Sthala means Land.',N'2016-02-10 09:20:12 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1005,N'Why is ‘Sthala Seva’ auspicious?',N'Offering anything to Lord is auspicious. Offering a space for Lord to reside is extremely auspicious and sacred. Constructing a temple is not a one-man accomplishment, and begins with Sthala Seva.  How do I sponsor:  You can sponsor by  1. In person: Visiting our Peetham and contact front desk. 2. Over the phone: Contact us at 732-809-1200 3. Visit our website: www.saidattanj.org/sthalaseva.html',N'2016-02-10 09:22:00 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1006,N'How is Sthala Seva different from temple construction?',N'Our temples have both the temple (building) and some space for religious activities. The entire premises need to be accommodated in land-space. This entire land-space need to be chosen at a particular place, direction, elevation and called a ‘Sthala’. Temple is next constructed on such a Sthala.',N'2016-02-10 09:22:26 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1007,N'Why do we need a separate temple?',N'We are living too far away from home in distant lands, and we have our own reasons for this migration. While we are away, the main thing which still keeps us close to our place of origin, our roots is our culture. Temples uphold such cultures. While each temple has its own unique way of upholding this culture, this temple is envisioned to take us close to our home by building in Shirdi style, the first of its kind outside India.',N'2016-02-10 09:22:47 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1008,N'Will the Mandir have other deities ?',N'Yes, the Mandir will also have many deities.',N'2016-02-10 09:23:07 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1009,N'Where will the temple be located ?',N'We are planning to acquire some land few miles from Sai Datta Peetham, NJ',N'2016-02-10 09:27:44 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1010,N'Will the new Mandir also be based on Yatha-Shakthi ?',N'Yes. We believe there is no reason to enforce cost to Peetham services. Dhaanam is the only virtue which we can associate with ourselves when our soul departs from this material body. We believe the ‘Yatha-Shakthi’ concept here encourages and enhances the ‘Dhaanam’ (Charitable service) attitude in common man, and hence shows the path for eternal bliss.',N'2016-02-10 09:28:03 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1011,N'Why do we need a bigger temple ?',N'As already mentioned, while we live away from our original homes, it is important to keep up our culture and tradition to keep up our individuality. Our lives can be compared to a river, constantly flowing/running very fast, while banks maintain the path/course. The river-course will change if there is not enough strong vegetation to hold the banks together. Temples are like vegetation on banks of a river. Our home, India, is still rich in its traditions and culture because of our places of worship, built hundreds of years back. And, we need more space to accommodate the devotees, the ritual-practices, the traditional and devotional events, which keeps up the culture live in our minds.',N'2016-02-10 09:28:21 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1012,N'What is the significance of Bhoodaan (Donating Land) ?',N'Donating towards land for a Mandir, the abode for God, is very auspicious and sacred. It is a rare opportunity. In ancient times, kings and rich land-lords used to donate huge land-masses for construction of temples. The fruits of such generous and un-selfish act are being enjoyed by their descendants and common man for generations together. Temples back in India, each of those, are at least hundred years old. History repeats itself and we once again have such a rare opportunity here in NJ. Please offer generously and may your generations benefit the fruit for years to come.',N'2016-02-10 09:28:38 AM')
INSERT INTO [saidattapeetham].[dbo].[SEVA_STHALA_FAQ]([ID],[QUESTION],[ANSWER],[DATETIME]) VALUES(1013,N'Why donation of $11 per person per family ?',N'We want all devotees to be able to participate in this Sthala Seva and hence all should be able to benefit the fruit of this Seva. We feel $11 per person per family would enable each and every individual to contribute towards this Sthala seva. While we anticipate a cost of at least USD 1_100_000 to acquire this land, devotees whole-hearted participation would make this lot easier and achievable. We anticipate that, if we have the funds, then we can complete this project by mid-2015. Donation towards land for temple construction is a once in life-time opportunity. Constructing a temple is not a one-man accomplishment. It is meant to be a group project, such that fruit needs to be enjoyed by all those in that group. We want all devotees to be part of this group. We request each donating person to inspire and encourage another family to donate. This is a rare opportunity, and such a rare opportunity is a good news, and it is a goodwill to share such good news so that we all can benefit the fruit.',N'2016-02-10 09:28:56 AM')
GO
print 'Inserted 12 records'

SET IDENTITY_INSERT [saidattapeetham].[dbo].[SEVA_STHALA_FAQ] OFF
GO

